database:
  type: postgresql
  host: 100.81.215.111
  port: 5432
  username: postgres
  password: $TTn120897$
  database_name: logistics
  driver: org.postgresql.Driver

spark-connect:
  host: 100.124.212.114
  port: 15002